site_name: "guanaco"
site_description: "guanaco doc"
site_author: "MoM"
edit_uri: ""
theme:
  logo: assets/logo.png
  # favicon: assets/favicon.png
  name: "material"
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.sections
repo_name: "guanaco"
repo_url: "https://github.com/momenaca/proyecto-guanaco"

extra_css:
  - ./stylesheets/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

###############################################################################################
# NAV STRUCTURE
###############################################################################################

nav:
  # --- HOME ---

  - Home:
      - index.md
      - Installation: home/installation.md
      # - Release notes: home/releases.md
      # - Roadmap: home/roadmap.md

    # --- DOCUMENTATION ---

  - Documentation:
      - Introduction:
          - How to read documentation: documentation/how_to_read_documentation.md
      - Some functionalities:
          - Data loading: documentation/1-data_loading.ipynb

  - Library:
      # - library/dataset.md

###############################################################################################
# PLUGINS
###############################################################################################

plugins:
  - search
  - minify:
      minify_html: true
  - mkdocs-jupyter:
      include_source: True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true

###############################################################################################
# EXTENSIONS
###############################################################################################

markdown_extensions:
  - markdown.extensions.toc:
      slugify: !!python/name:pymdownx.slugs.uslugify
      permalink: ""
  - markdown.extensions.admonition:
  - markdown.extensions.smarty:
      smart_quotes: false
  - pymdownx.betterem:
  - markdown.extensions.attr_list:
  - markdown.extensions.def_list:
  - markdown.extensions.tables:
  - markdown.extensions.abbr:
  - markdown.extensions.footnotes:
  - markdown.extensions.md_in_html:
  - pymdownx.superfences:
      preserve_tabs: true
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php-inline
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite:
      custom_inline:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.inline_mathjax_format
  - pymdownx.tilde:
  - pymdownx.caret:
  - pymdownx.smartsymbols:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.escapeall:
      hardbreak: True
      nbsp: True
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.progressbar:
  - pymdownx.arithmatex:
  - pymdownx.mark:
  - pymdownx.striphtml:
  - pymdownx.keys:
      separator: "\uff0b"
  - pymdownx.details:
  - pymdownx.tabbed:
  - pymdownx.saneheaders:
